### ISSUE TITLE
Missing auth callback on FAPI.provision

### ISSUE THREAD

**Issue by gluafamichl** [tpm2-software/tpm2-pytss#173]
H there,

I'm using Ubuntu 20.04, python 3.8.5 and latest master builds from tss and pytss. I'm just playing around and tried the following code, which looked quite easy and simple to get a random number:

>     with FAPI() as fapi:
>         fapi.provision()
>         print(fapi.get_random(32))

Now I get the following error message, am I missing something? I think the problem is the missing auth callback.

> ERROR:fapi:src/tss2-fapi/fapi_util.c:411:ifapi_set_auth() Authorization callback not defined. ErrorCode (0x0006002a) 
> ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:893:Fapi_Provision_Finish() Set auth value ErrorCode (0x0006002a) 
> ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x0006002a) Provision 
> Traceback (most recent call last):
>   File "cli.py", line 116, in <module> fapi.provision()
>   File "lib/python3.8/site-packages/tpm2_pytss/FAPI.py", line 211, in provision
>     _chkrc(
>   File "lib/python3.8/site-packages/tpm2_pytss/utils.py", line 17, in _chkrc
>     if acceptable is not None and (rc == acceptable or rc in acceptable):
> TypeError: argument of type 'int' is not iterable

Thanks and best regards.

**Comment by williamcroberts** [comment]
I fixed it in PR #174. If you drop the "fapi.provision" and use tss2_provision from the tpm2-tools project, it should work. Note that if you're using the simulator, you need to add option `ek_cert_less` to your fapi config:
```bash
sudo vim /usr/local/etc/tpm2-tss/fapi-config.json
```
Sample of my config:
```json
{
     "profile_name": "P_ECCP256SHA256",
     "profile_dir": "/usr/local/etc/tpm2-tss/fapi-profiles/",
     "user_dir": "~/.local/share/tpm2-tss/user/keystore",
     "system_dir": "/usr/local/var/lib/tpm2-tss/system/keystore",
     "tcti": "",
     "ek_cert_less": "yes",
     "system_pcrs" : [],
     "log_dir" : "/usr/local/var/run/tpm2-tss/eventlog/"
}
```

**Comment by gluafamichl** [comment]
Thanks, this fixes the list error, but I'm still getting the Authorization callback not defined error.

**Comment by williamcroberts** [comment]
hrmm, I'm running the same setup, I cant replicate this error. Do you have multiple version of tpm2-tss installed?

**Comment by gluafamichl** [comment]
Ah, yes, you are right. I have the master branch and a previous branch. After removing the old branch it works like a charm.
Thanks for your really fast help.
